config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'games#index'
  get '/games/:id', to: 'games#show', as: 'game'

  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/signup', to: 'users#new', as: 'signup'
  post '/users', to: 'users#create'

  post '/gameplays', to: 'gameplays#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :gameplays
end

app/models/gameplay.rb
class Gameplay < ApplicationRecord
  belongs_to :game, optional: true
  belongs_to :user, optional: true

  def self.showTop3Scores(game_id)
    self.where(game_id: game_id).order('score DESC').limit(3)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Validations
  validates :first_name, :last_name, :password, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 100 }

  has_many :gameplays
  has_secure_password

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/gameplays_controller.rb
class GameplaysController < ApplicationController

  def create
    if current_user
      @gameplay = Gameplay.create({score: params[:score],
                                   user_id: current_user[:id],
                                   game_id: params[:game_id] })
    end
    
    render :json => Gameplay.showTop3Scores(params[:game_id]).to_json(:include => :user)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
    @user = User.confirm(user_params)
    if @user
      login(@user)
      flash[:notice] = "Welcome back #{@user.first_name}."
      redirect_to root_path
    else
      flash[:error] = 'Incorrect email or password.'
      redirect_to login_path
    end
  end

  def destroy
    logout
    flash[:notice] = 'Successfully logged out.'
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.create
  end

  def create
    @user = User.create(user_params)
    if @user.id
      login(@user)
      redirect_to root_path
    else
      flash[:error] = "#{@user.errors.details[:email][0][:value]} #{@user.errors.messages[:email][0]}"
      redirect_to signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gameplays_helper.rb
module GameplaysHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logout
    @current_user = session[:user_id] = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<div class="game-board">
  <div class="chooseSongContainer">
    <% @games.each do |game| %>
      <%= link_to game_path(game.id) do %>
        <div class="level <%= game.level.downcase %>">
          <%= game.title %><br>
          by <%= game.artist %><br>
          Level: <%= game.level %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<%= javascript_include_tag "games.js" %>

<div class="game-board">
  <div class="readyContainer">
    <input type="submit" value="Ready?" class="btn start-btn" data-disable-with="start" />
  </div>
  <div class="columnsContainer">
    <div class="data-pattern" hidden="hidden" data-pattern='<%= @game.pattern.to_json %>'></div>
    <div class="bar"></div>
    <div class="column column-d">D</div>
    <div class="column column-f">F</div>
    <div class="column column-j">J</div>
    <div class="column column-k">K</div>
  </div>

  <div class="gameOverContainer">
    <p>GAME OVER<br>
      <i class="fa fa-frown-o" aria-hidden="true"></i>
    </p>
    <input type="submit" name="commit" value="Try Again" class="btn play-again-btn" data-disable-with="play">
    <input type="submit" name="commit" value="Exit" class="btn exit-btn" data-disable-with="exit">
  </div>

  <div class="gameCompleted">
    <table class="top3Scores">
      <th colspan="3">Top 3 Scores</i>
    </table>
    <input type="submit" name="commit" value="Try Again" class="btn play-again-btn" data-disable-with="play">
    <input type="submit" name="commit" value="Exit" class="btn exit-btn" data-disable-with="exit">
  </div>
</div>

<p class='game_id' hidden="hidden"><%= @game.id %></p>
<audio controls preload="auto">
 <source src="<%= @game.file_path %>" type="audio/ogg">
</audio>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KeyDanceRevolution</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Coming+Soon" rel="stylesheet">
  </head>

  <body>
    <%= link_to root_path, class: 'home links' do %>
      <div class="logoContainer">
        <%= image_tag('/assets/logo.png', class: 'logo') %>
        <h1>KeyDR</h1>
      </div>
    <% end %>

    <% flash.each do |type, message| %>
      <p class='flash-msg'><%= message %></p>
    <% end %>
    <div class='score-board'>
      <p class='score'></p>
      <div class="login-signup">
        <% if current_user %>
        Welcome <%= current_user.first_name %><br>
        <i class="fa fa-sign-out" aria-hidden="true"></i>
        <%= link_to 'Log Out', logout_path, class: 'links' %>
        <% else %>
        Hi there.<br>
        <i class="fa fa-sign-in" aria-hidden="true"></i>
        <%= link_to 'Log In', login_path, class: 'links' %><br>
        <i class="fa fa-user-plus" aria-hidden="true"></i>
        <%= link_to 'Sign Up', signup_path, class: 'links' %>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= javascript_include_tag "users.js" %>

<% if current_user %>
  <% flash[:error] = 'Please log out to sign up.'%>
<% else %>
  <div class="game-board screen">
    <%= form_for @user do |f| %>
      <div class='screen-icon'>
        <i class="fa fa-user-plus" aria-hidden="true"></i>
      </div>
      <%= f.text_field :first_name, placeholder: 'First Name', class: 'signup-inputs f-name' %>
      <p class='f-name-err'>What's your first name?</p>
      <%= f.text_field :last_name, placeholder: 'Last Name', class: 'signup-inputs l-name' %>
      <p class='l-name-err'>What's your last name?</p>
      <%= f.email_field :email, placeholder: 'Email', class: 'signup-inputs email' %>
      <p class='email-err'>Please type a valid email address please.</p>
      <%= f.password_field :password, placeholder: 'Password', class: 'signup-inputs password' %>
      <p class='min-length-err'>Password must be more than 8 characters.</p>
      <%= f.password_field :password, placeholder: 'Confirm Password', class: 'signup-inputs c-password' %>
      <p class='not-match-err'>Repeat your new password.</p>
      <%= f.submit "Sign Up", class: 'btn signup-btn', disabled: true %>
    <% end %>
  </div>
<% end %>